homepage:
    pattern: /
    defaults: { _controller: AndroBundle:Main:homepage }

contact:
    pattern: /contact
    defaults: { _controller: AndroBundle:Contact:show }

archives:
    pattern: /archives/{page}
    defaults: { _controller: AndroBundle:Article:archives, page: 1 }

eula:
    pattern: /eula
    defaults: { _controller: AndroBundle:Main:eula }

screenshots:
    pattern: /screenshots
    defaults: { _controller: AndroBundle:Main:screenshots }

donate:
    pattern: /donate
    defaults: { _controller: AndroBundle:Main:donate }

article_show:
    pattern: /article/{id}/{slug}
    defaults: { _controller: AndroBundle:Article:show }

_article_atom:
    pattern: /articles/atom
    defaults: { _controller: AndroBundle:Article:atom, _format: atom }

beta:
    pattern: /beta
    defaults: { _controller: AndroBundle:Beta:show }

_beta_download:
    pattern: /beta/download
    defaults: { _controller: AndroBundle:Beta:download }

_beta_latest:
    pattern: /beta/latest
    defaults: { _controller: AndroBundle:Beta:latest }

_tip:
    pattern: /tip/{lang}/{date}
    defaults: { _controller: AndroBundle:Tip:show, date: null }

_quickstart:
    pattern: /quickstart/{version}/{lang}
    defaults: { _controller: AndroBundle:QuickStart:show }

_crash_report:
    pattern: /crashreport
    defaults: { _controller: AndroBundle:CrashReport:add }
    requirements: { _method: post }

_changelog:
    pattern: /changelog/{version}
    defaults: { _controller: AndroBundle:ChangeLog:show }

# Security

login:
    pattern: /login
    defaults: { _controller: AndroBundle:Security:login }

_login_check:
    pattern: /login_check

_logout:
    pattern: /logout