# Dashboard
admin_dashboard:
    pattern: /
    defaults: { _controller: AdminBundle:Main:dashboard }

# Article
admin_base_article:
    resource: 'routing/article.yml'
    prefix:   /article

# Donator
admin_base_donator:
    resource: 'routing/donator.yml'
    prefix:   /donator

# Beta Release
admin_base_beta_release:
    resource: 'routing/beta_release.yml'
    prefix:   /beta

# User
admin_base_user:
    resource: 'routing/user.yml'
    prefix:   /user

# Tip
admin_base_tip:
    resource: 'routing/tip.yml'
    prefix:   /tip

# Tip Holiday
admin_base_tip_holiday:
    resource: 'routing/tip_holiday.yml'
    prefix:   /holiday

# CrashReport
admin_base_crash_report:
    resource: 'routing/crash_report.yml'
    prefix:   /crash

# QuickStart
admin_base_quick_start:
    resource: 'routing/quick_start.yml'
    prefix:   /quickstart

# ChangeLog
admin_base_change_log:
    resource: 'routing/change_log.yml'
    prefix:   /changelog

# Version
admin_version:
    pattern: /version
    defaults: { _controller: AdminBundle:Version:index }

# AndroIRC version
admin_base_androirc_version:
    resource: 'routing/androirc_version.yml'
    prefix:   /version/androirc

# Android version
admin_base_android_version:
    resource: 'routing/android_version.yml'
    prefix:   /version/android
